# Preparing the Canvas

Consider the following scenario, you are asked to perform analysis on some data, we would all agree that it would be a tedious task to complete our analysis using the command line interface. The RStudio IDE (or any IDE for that matter) provides us with the freedom to reproduce the execution of our code sequentially to be executed on someone else along with host of other important advantage.

Now as it happens at the end of most analysis we are required to produce a report to be shared. This report in general takes one of the following forms.

- A Spreadsheet.
- A text document.
- A powerpoint presentation.

thinking on similar lines as we did while comparing the *CMD line* to a *text editor* we see that it would really be a tedious job to produce reports especially if the reports are going to be repetative and similar in nature.Before we start writing a single line of code, I encourage you to ask yourself, *what is my output file format going to be ?*.

**Beginning at the end.**

R Studio provides us with the following (along with many other) output formats in which we can share our analysis.

- R Markdown
- Dashboards
- Web Pages (Blogs and Books)
- Web Applications

We'll skim on the surface of each of these output formats in the following chapters.