## Dashboards

Dashboards are a great tool to represent live data or data in forms of reports. The [`flexdashboard`](http://rmarkdown.rstudio.com/flexdashboard/) library allows us to do just that. It enables you to easily create flexible, attractive, interactive dashboards with R. Authoring and customization of dashboards is done using [R Markdown](http://rmarkdown.rstudio.com/) and you can optionally include [Shiny](http://shiny.rstudio.com/)(more on it later) components for additional interactivity.

Highlights of the flexdashboard package include:

-    Support for a wide variety of components including interactive htmlwidgets; base, lattice, and grid graphics; tabular data; gauges; and value boxes.

-    Flexible and easy to specify row and column-based layouts. Components are intelligently re-sized to fill the browser and adapted for display on mobile devices.

-    Extensive support for text annotations to include assumptions, contextual narrative, and analysis within dashboards.

-    Storyboard layouts for presenting sequences of visualizations and related commentary.

-    By default dashboards are standard HTML documents that can be deployed on any web server or even attached to an email message. You can optionally add Shiny components for additional interactivity and then deploy on Shiny Server or shinyapps.io.


You can explore the gallery of the dashboards at <https://rmarkdown.rstudio.com/flexdashboard/examples.html>


Additional learning resource is [here](https://blog.rstudio.com/2016/05/17/flexdashboard-easy-interactive-dashboards-for-r/)